id: DCEC9E46E
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-01-18T10:53:29+00:00'
last_modified: '2022-05-26T14:26:27.337564+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/a7eec5e12ddce18d0ed1dbb732a42cf48f94dd09/openpecha/formatters/hfml.py
source_metadata:
  base:
    8cc6:
      image_group_id: I1PD95885
      title: ཆོམ་རྐུན་བཅིང་བ།
      total_pages: 1648
      order: 40
      base_file: 8cc6.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
